import type { Metadata } from 'next'

import 'bootstrap/dist/css/bootstrap.css';
import './globals.css'
import 'boundless-commerce-components/dist/styles.css';
import 'boundless-checkout-react/dist/index.css';

import WrapperForCart from "@/components/wrapperForCart";
import CartFAB from "@/components/cart/fab";
import {ReactNode} from 'react';

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: ReactNode}) {
  return (
    <html lang="en">
      <body>
        <WrapperForCart>
          {children}
          <CartFAB />
        </WrapperForCart>
      </body>
    </html>
  );
}
